# Generated by Django 6.0.6 on 2026-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('ABOUT', 'About'), ('COURSES', 'Courses'), ('GALLERY', 'Gallery'), ('SHOP', 'Shop'), ('CONTACT', 'Contact'), ('MENTOR', 'Mentor'), ('SUCCESS_STORY', 'Success Story'), ('EVENT', 'Event')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=260)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
