# Generated by Django 6.0.6 on 2026-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='mentors/')),
                ('bio', models.TextField()),
                ('is_top', models.BooleanField(default=False, help_text='Mark as Top Mentor to show on the about page preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mentors',
                'ordering': ['-is_top', 'name'],
            },
        ),
    ]
