# Generated by Django 6.0.6 on 2026-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(null=True, upload_to='mentors/'),
        ),
    ]
