# Generated by Django 6.0.6 on 2026-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='home/heroes')),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='Carousel order. it is 0 indexing so 0 mean first banner')),
            ],
            options={
                'db_table': 'home_heroes',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Full YouTube video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'home_videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
