# Generated by Django 6.0.6 on 2026-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
